### ISSUE TITLE
Regex in pattern attribute of input tags have backslashes erroneously stripped out

### ISSUE THREAD

**Issue by ahubl-mz** [StackStorm/ewc#4]
When you put URLs into the API and Auth fields of BWD:

<img width="917" alt="screen shot 2018-01-12 at 6 05 10 pm" src="https://user-images.githubusercontent.com/32691407/34956614-d292d170-f9de-11e7-8b77-b2a75d147fcf.png">

the `pattern` attribute of the HTML `input` elements has what _should_ be `\s` to disallow whitespace characters in the URL, but the backslashes are getting stripped out so it’s actually disallowing `s` characters in the URL:

<img width="442" alt="screen shot 2018-01-12 at 6 06 30 pm" src="https://user-images.githubusercontent.com/32691407/34956626-e115f16e-f9de-11e7-9dd8-c61e4fa249d2.png">

So when your domain is https://stackstorm.example.com, the `input` element prevents you from even successfully filling out that field. This entirely prevents our users from logging in to the Workflow Designer and getting access to all of the actions in packs we have installed.

However, once I open up developer tools and add the backslashes to correct the `pattern`, everything works as expected.

**Comment by blag** [comment]
This is fixed. Closing.

**Comment by blag** [comment]
Thank you for reporting!
